[package]
name = "acorn"
version = "0.1.0"
edition = "2021"
description = "Safe Rust bindings for AcornDB"
license = "MIT"

[dependencies]
acorn-sys = { path = "../acorn-sys" }
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
