[package]
name = "acorn-sys"
version = "0.1.0"
edition = "2021"
description = "Raw FFI bindings to AcornDB NativeAOT shim"
license = "MIT"
links = "acornshim"

[build-dependencies]
bindgen = "0.70"
cc = "1"

[dependencies]
libc = "0.2"
